### ISSUE TITLE
Task-7 Observe life stages does not specify location

### ISSUE THREAD

**Issue by manuelciosici** [allenai/ScienceWorld#18]
The task 7 description omits the animal location, thus requiring agents to explore the environment until they find the named animal. This seems unnatural as we would not issue such a vague task in human-to-human conversation. This issue affects both variants of task 7.

https://github.com/allenai/ScienceWorld/blob/22a70ce40e23ac9ca28e03f5b6f176a2922a8f50/simulator/src/main/scala/scienceworld/tasks/specifictasks/TaskIdentifyLifeStages1.scala#L134

Despite the lack of location, SW sets the goal of the agent arriving at the animal's location:

https://github.com/allenai/ScienceWorld/blob/22a70ce40e23ac9ca28e03f5b6f176a2922a8f50/simulator/src/main/scala/scienceworld/tasks/specifictasks/TaskIdentifyLifeStages1.scala#L127

This code suggests that the animal location should have been defined. Suppose the task is meant not to specify the location. In that case, the goal above is nonsensical since any agent (human or machine) would arrive at the location by exploration rather than intentionally. While most animals in task 7 are what one would expect to live outside (e.g., elephant, wolf), some can be pets (e.g., parrot, turtle) and thus, would be expected to live somewhere in the house.

**Comment by PeterAJansen** [comment]
Hi @manuelciosici , 

While some tasks do specify where materials are (e.g. the electrical tasks usually let the agent know that the items are in the workshop), some don't both as an explicit test of the agent's ability to explore, as well as its knowledge of common-sense locations (e.g. outside is a high-probability location for animals, a green house is a high-probability location for plants, etc).  So these don't appear to be issues, and are by design. 

For the subgoals, there are frequently extended subgoals to help nudge reinforcement learning agents towards a correct solution, even if information regarding those goals isn't explicitly provided in the task description.  For example, here, being in the same location as an observable task-critical object (like an animal for Task 7) is frequently a subgoal, so that the agent has some small reward signal to help learn that there's something important present.  Another way of looking at this is that (if I remember correctly) the subgoals provide a small reward for placing e.g. water in a container for the water boiling task variation, even though it isn't explicitly mentioned that liquids need to be in containers in the task description.  These subgoals can be though of as both small tests and small rewards for an agent using the appropriate domain-specific and commonsense-reasoning skills to solving some small part of the task in a (usually) canonical way. 

best wishes,
Peter

**Comment by manuelciosici** [comment]
@PeterAJansen Thank you for the explanation. It makes sense not to specify the location as a test of the agent's common-sense knowledge.

I just noticed that the location for plants is still `outside` and not `green house`:

https://github.com/allenai/ScienceWorld/blob/22a70ce40e23ac9ca28e03f5b6f176a2922a8f50/simulator/src/main/scala/scienceworld/tasks/specifictasks/TaskIdentifyLifeStages2.scala#L26

Is that also intentional?

**Comment by manuelciosici** [comment]
While we are discussing locations, is `green house` vs. `greenhouse` ([dictionary](https://www.merriam-webster.com/dictionary/greenhouse)) intentional or a typo?

**Comment by PeterAJansen** [comment]
@manuelciosici plant tasks typically happen `outside` or in the `green house`, but the simulator is designed to be generic, so it is not limited to this.  An agent could (I believe) take a cup from the kitchen, go outside, take the shovel, dig a hole, fill the cup with dirt, put a seed in the cup, place it in the art studio, frequently give it water, and (eventually) a plant should grow.  What hints that are provided in the task description are just meant to be occasional hints for canonical solutions, but many solutions are possible. 

It looks like the misspelling `green house` might have made it into the simulation, and we'll have to fix that in the next version.

**Comment by MarcCote** [comment]
Typo is fix in https://github.com/allenai/ScienceWorld/pull/26
